version: '3'

services:
  nuxt:
    build:
      context: .
      dockerfile: ./images/nuxt/Dockerfile
    container_name: nuxt
    working_dir: /var/www/dices/front
    restart: on-failure
    env_file: .env
    volumes:
      - .:/var/www/dices/front
    ports:
      - "3081:3000"